### ISSUE TITLE
配置格式错误导致报错

### ISSUE THREAD

**Issue by kkxue** [idcos/osinstall-server#20]
```
# ./cloudboot-server 
0x0, *osinstallserver.OsInstallServer
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4022de]

goroutine 1 [running]:
main.runServer(0xc20809d2c0)
	/usr/yunji/osinstall-server/src/cmd/cloudboot-server/main.go:52 +0x3be
main.func·001(0xc20809d2c0)
	/usr/yunji/osinstall-server/src/cmd/cloudboot-server/main.go:37 +0x77
github.com/codegangsta/cli.(*App).Run(0xc2080ca840, 0xc20800a000, 0x1, 0x1, 0x0, 0x0)
	/usr/yunji/osinstall-server/vendor/src/github.com/codegangsta/cli/app.go:201 +0x1517
main.main()
	/usr/yunji/osinstall-server/src/cmd/cloudboot-server/main.go:40 +0x23c

goroutine 2 [runnable]:
runtime.forcegchelper()
	/root/go/src/runtime/proc.go:90
runtime.goexit()
	/root/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
	/root/go/src/runtime/mgc0.go:82
runtime.goexit()
	/root/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 4 [runnable]:
runtime.runfinq()
	/root/go/src/runtime/malloc.go:712
runtime.goexit()
	/root/go/src/runtime/asm_amd64.s:2232 +0x1
```

原因是配置文件写错了，需要加上外面的{}
```
# cat  /etc/cloudboot-server/cloudboot-server.conf
{
    "repo": { "connection": "root:root@tcp(localhost:3306)/cloudboot?charset=utf8&parseTime=True&loc=Local" },
    "osInstall":{ "pxeConfigDir":"/var/lib/tftpboot/pxelinux.cfg" }
}
```

**Comment by kkxue** [comment]
这种报错是不是要handle下

**Comment by voidint** [comment]
这个bug已经在develop分支修复了，等待被合并到master分支。 https://github.com/idcos/osinstall-server/issues/7
